# ---------------- SERVER ----------------
server.port=${PORT:10000}
server.address=0.0.0.0

# \uD83D\uDD25 DISABLE DATABASE (REQUIRED)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# \uD83D\uDD25 FAST START
spring.main.lazy-initialization=true

# ---------------- LOGGING ----------------
logging.level.org.springframework=ERROR

# ---------------- ERROR HANDLING ----------------
server.error.include-message=always