# ---------------- SERVER ----------------
server.port=${PORT:8080}

# ---------------- DATABASE ----------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# ---------------- CONNECTION POOL ----------------
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

# ---------------- JPA ----------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ---------------- LOGGING ----------------
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=OFF

# ---------------- ERROR HANDLING ----------------
server.error.include-message=always